exclude: 'renv'
repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.0.0.9015
    hooks:
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: roxygenize
    -   id: use-tidy-description
    -   id: deps-in-desc
-   repo: https://github.com/petrbouchal/ptrr
    rev: 3a86aaf608d6e3177dedf9214c7834f0819eb001
    hooks:
    -   id: no-view-statement
