exclude: 'renv'
repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.1.3
    hooks:
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: roxygenize
    -   id: use-tidy-description
    -   id: deps-in-desc
-   repo: https://github.com/petrbouchal/ptrr
    rev: ab1268e
    hooks:
    -   id: no-view-statement
