# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

warnings_are_errors: false

r_packages:
  - sp
  - sf
  - rgdal
  - rgeos

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libjq-dev

r_github_packages:
  - r-lib/covr
  - r-quantities/errors
  - JanCaha/CzechData

cache: packages
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
